import { runAllAgents } from '../../../lib/agents'
import type { AgentRun } from '../../../lib/agentStore'

/**
 * Daily email digest: runs all agents fresh, composes a brief, and emails it
 * via Resend. Triggered by Vercel Cron (1×/day) — and manually for testing.
 * Read-only/watch-only: the email reports what the agents found, nothing else.
 */
export const dynamic = 'force-dynamic'
export const maxDuration = 60

function authorized(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  if (req.headers.get('authorization') === `Bearer ${secret}`) return true
  return new URL(req.url).searchParams.get('key') === secret
}

const TONE: Record<string, string> = { Active: '#3a8a4f', Alert: '#b3261e', Idle: '#8a8a8a' }

function sourceLink(a: AgentRun): string {
  if (!a.sourceUrl) return ''
  return `<div style="margin-top:7px;"><a href="${a.sourceUrl}" target="_blank" style="font:600 12px/1.5 -apple-system,Helvetica,Arial,sans-serif;color:#b08a3e;text-decoration:none;">↗ ${a.sourceLabel || 'View source'}</a></div>`
}

function agentBlock(a: AgentRun): string {
  const color = TONE[a.status] ?? '#8a8a8a'
  return `
    <tr><td style="padding:16px 0;border-bottom:1px solid #eceae4;">
      <div style="font:600 11px/1 -apple-system,Helvetica,Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:#9a9488;">
        ${a.name}
        <span style="display:inline-block;margin-left:8px;padding:2px 8px;border-radius:20px;background:${color}1a;color:${color};font-size:9.5px;">${a.status}</span>
      </div>
      <div style="font:600 15px/1.4 Georgia,serif;color:#1d1b16;margin:7px 0 4px;">${a.headline}</div>
      <div style="font:400 13px/1.6 -apple-system,Helvetica,Arial,sans-serif;color:#4a463f;">${a.finding}</div>
      ${a.detail ? `<div style="font:400 12px/1.5 -apple-system,Helvetica,Arial,sans-serif;color:#9a9488;margin-top:5px;">${a.detail}</div>` : ''}
      ${sourceLink(a)}
    </td></tr>`
}

function leadBlock(a: AgentRun): string {
  return `
    <table role="presentation" width="100%" style="background:#fbf6ea;border:1px solid #ecdfc0;border-radius:12px;margin-bottom:8px;">
      <tr><td style="padding:16px 18px;">
        <div style="font:600 11px/1 -apple-system,Helvetica,Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:#b08a3e;">✦ ${a.name}</div>
        <div style="font:600 17px/1.35 Georgia,serif;color:#1d1b16;margin:8px 0 5px;">${a.headline}</div>
        <div style="font:400 13.5px/1.6 -apple-system,Helvetica,Arial,sans-serif;color:#3f3b34;">${a.finding}</div>
        ${a.detail ? `<div style="font:600 12px/1.5 -apple-system,Helvetica,Arial,sans-serif;color:#b08a3e;margin-top:8px;">▸ Watch: ${a.detail}</div>` : ''}
      </td></tr>
    </table>`
}

function composeHtml(runs: AgentRun[], dateLabel: string): string {
  const alerts = runs.filter((r) => r.status === 'Alert').length
  const cio = runs.find((r) => r.id === 'cio-brief')
  const desks = runs.filter((r) => r.id !== 'cio-brief')
  return `<!doctype html><html><body style="margin:0;background:#f4f1ea;padding:24px;">
    <table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#fffdf8;border-radius:14px;border:1px solid #e7e3da;">
      <tr><td style="padding:24px 28px 8px;">
        <div style="font:600 12px/1 -apple-system,Helvetica,Arial,sans-serif;letter-spacing:.16em;text-transform:uppercase;color:#b08a3e;">♞ Cheval Holdings</div>
        <div style="font:600 22px/1.2 Georgia,serif;color:#1d1b16;margin:8px 0 2px;">Daily Market Brief</div>
        <div style="font:400 12px/1.4 -apple-system,Helvetica,Arial,sans-serif;color:#9a9488;">${dateLabel}${alerts ? ` · ${alerts} alert${alerts > 1 ? 's' : ''}` : ''} · read-only research</div>
      </td></tr>
      <tr><td style="padding:4px 28px 20px;">
        ${cio ? leadBlock(cio) : ''}
        <div style="font:600 10px/1 -apple-system,Helvetica,Arial,sans-serif;letter-spacing:.14em;text-transform:uppercase;color:#b3afa6;margin:18px 0 -4px;">By desk</div>
        <table role="presentation" width="100%">${desks.map(agentBlock).join('')}</table>
        <div style="font:400 11px/1.5 -apple-system,Helvetica,Arial,sans-serif;color:#b3afa6;margin-top:18px;">
          Generated by the Cheval agents from live market data. Research only — the system reads &amp; reports, it never moves funds.
        </div>
      </td></tr>
    </table>
  </body></html>`
}

export async function GET(req: Request) {
  if (!authorized(req)) return Response.json({ error: 'unauthorized' }, { status: 401 })

  const token = process.env.APIFY_TOKEN
  const apiKey = process.env.RESEND_API_KEY
  const from = process.env.AGENT_DIGEST_FROM
  const to = process.env.AGENT_DIGEST_TO
  if (!token) return Response.json({ sent: false, error: 'no APIFY_TOKEN' })
  if (!apiKey || !from || !to) {
    return Response.json({ sent: false, error: 'Resend not configured (RESEND_API_KEY / AGENT_DIGEST_FROM / AGENT_DIGEST_TO)' })
  }

  const origin = new URL(req.url).origin
  const runs = await runAllAgents(origin, token)
  const dateLabel = new Date().toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric', timeZone: 'America/New_York',
  })
  const alerts = runs.filter((r) => r.status === 'Alert').length
  const subject = `Cheval Daily Brief — ${dateLabel}${alerts ? ` · ${alerts} alert${alerts > 1 ? 's' : ''}` : ''}`

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { authorization: `Bearer ${apiKey}`, 'content-type': 'application/json' },
      body: JSON.stringify({
        from,
        to: to.split(',').map((s) => s.trim()),
        subject,
        html: composeHtml(runs, dateLabel),
      }),
    })
    const body = (await res.json()) as { id?: string; message?: string }
    if (!res.ok) return Response.json({ sent: false, error: body.message ?? `Resend ${res.status}` })
    return Response.json({ sent: true, id: body.id, agents: runs.length, alerts })
  } catch (e) {
    return Response.json({ sent: false, error: String(e).slice(0, 120) })
  }
}
